<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post">
            <?php if($this->view->erroCadastro) { ?>
                <small class="form-text text-danger">Erro ao tentar realizar cadastro, o Usuario inserido já existe, tente alterar o email ou o nome</small>
            <?php  }    ?>
              <div class="form-group">
                <input type="text" value="<?php echo $this->view->usuario['nome']; ?>" class="form-control" name="nome" placeholder="Nome">
              </div>
              
              <div class="form-group">
                <input type="text" class="form-control" name="email" placeholder="E-mail" value="<?php echo $this->view->usuario['email']; ?>">
              </div>

              <div class="form-group">
                <input type="password" class="form-control" name="senha" placeholder="Senha" value="<?php echo $this->view->usuario['senha']; ?>">
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>
             
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  