<html>
	<head>
		<meta charset="utf-8" />
		<title>Twitter-CLone</title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

		<link rel="stylesheet" type="text/css" href="./app//style.css">
<style>
	html, body {
  height: 100%;
}

body {
	font-family: "Segoe UI", Arial, sans-serif;
	background-color: white;
	color: black;
}

h1 {
	display: block;
    font-size: 2em;
    margin-block-start: 0.67em;
    margin-block-end: 0.67em;
    margin-inline-start: 0px;
    margin-inline-end: 0px;
    font-weight: bold;
}

h2 {
	display: block;
    font-size: 1.5em;
    margin-block-start: 0.83em;
    margin-block-end: 0.83em;
    margin-inline-start: 0px;
    margin-inline-end: 0px;
    font-weight: bold;
}

.banner {
	height: 100%;
	background-color: #1da1f2;
}

.title {
	color: #1da1f2;
	font-size: 27px;
    line-height: 32px;
}

.subtitle {
	color: #14171a;
    font-size: 18px;
    line-height: 24px;
    margin: 16px auto;
}

.form-control {
	background-color: #fff;
    border: 1px solid #e6ecf0;
    border-radius: 3px;
}

.comunicacao {
	flex-direction: row;
	flex-wrap: wrap;
	justify-content: center;
}

.communicationItem {
	color: #fff;
    display: -moz-box;
    display: -ms-flexbox;
    display: flex;
    font-size: 18px;
    font-weight: bold;
    line-height: 24px;
    margin: 48px auto;
    position: relative;
}

.menu {
    background:#1E90FF;
    height: 46px;
    border-bottom: 1px solid rgba(0,0,0,0.25);
    position: fixed;
    top: 0;
    right: 0;
    left: 0;
    z-index: 1000;
}
.menuItem{
	margin-top: 5px;
	padding: 5px;
    font-size: 13px;
    font-weight: bold;
    color: white;
    text-decoration: none;
    margin-right: 25px;
}

.menuItem:hover {
	border-radius: 50px;
	background-color: black;
	padding: 5px;
    font-size: 13px;
    font-weight: bold;
    color: #1DA1F2;
    text-decoration: none;
    margin-right: 25px;

}

.menuIco {
    width: 31px;
    height: 23px;
    position:absolute;
    top:50%;
    left:50%;
    margin-top:-10px;
    margin-left:-15px;
}

.perfil {
	color: black;
    border: 1px solid royalblue;
    background: #363636;
    position: relative;
    margin-bottom: 10px;
    display: block;
    width: 100%;
}

.perfilTopo {
    height: 95px;
    background-color: #1DA1F2
}

.perfilPainel {
    padding-right: 10px;
    padding-left: 10px;
}

.perfilPainelNome {
    font-weight: bold;
    font-size: 18px;
    line-height: 25px;
}

.perfilPainelItem  {
    color: black;
    font-size: 12px;
    font-weight: bold;
    letter-spacing: .02em;
    line-height: 16px;
    overflow: hidden;
    transition: color .15s ease-in-out;
}

.perfilPainelItemValor {
    display: block;
    font-size: 18px;
    font-weight: bold;
    padding-top: 3px;
    transition: color .15s;
    color: grey !important;
}

.tweetBox {
	background: black;
    border-top-left-radius: inherit;
    border-top-right-radius: inherit;
    border: 1px solid #e6ecf0;
    
    padding:25px;
	margin-bottom: 8px;
}

.quemSeguir {
    border: 1px solid #e6ecf0;
	box-shadow: #191970 3px 3px 8px;
	background: black;
    position: relative;
    margin-bottom: 10px;
    display: block;
    color: white;
    width: 100%;
    padding-right: 10px;
    padding-left: 10px;
    padding-bottom: 10px;
}

.quemSeguirTitulo {
    font-weight: bold;
    font-size: 18px;
    line-height: 25px;
}

.quemSeguirTxt, .quemSeguirTxt:hover {
    color: #1DA1F2;
    text-decoration: none;
    font-size: 12px;
    line-height: 16px;
}

.tweet {

    padding:15px;
    border: 2px solid royalblue;
    cursor: pointer;
	margin-bottom: 15px;
	border-radius: 10px;
	color:#E0FFFF;
	background:#9C9C9C;
	/* box-shadow: #5F9EA0 4px 2px 8px; */
}

.tweet:hover {
    background-color: #20B2AA;
	/* box-shadow: black 4px 2px 8px; */
}
</style>
	</head>

	<body >
		<?php $this->content() ?>
	</body>

</html>