<link rel="stylesheet" type="text/css" href="./app//style.css">
<link rel="stylesheet" href="./style.css">
<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<!-- <img src="/img/twitter_logo.png" class="menuIco" /> -->
			<i style="margin-left: 240%;" class="fab fa-twitter fa-3x "></i>
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?php foreach($this->view->info_usuario as $dados_ind => $dados) {echo $dados;}; ?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?php foreach($this->view->info_totaltweets as $dados_ind => $dados) {echo $dados;} ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?php foreach($this->view->info_totalseguindo as $dados_ind => $dados) {echo $dados;} ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?php foreach ($this->view->info_totalseguidores as $dados_ind => $dados) {echo $dados;} ?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="post" action="/tweet">
						<textarea style="border: 1px solid black;border-radius:20px" name="tweet" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-dark">Tweet</button>
						</div>

					</form>
				</div>
			</div>
<?php foreach($this->view->tweets as $id_tweet => $dados){ ?>
			<div class="row tweet">
				<div class="col">
					<p style="color:white"><strong><?php echo $dados['nome']; ?></strong> <span style="color:whitesmoke"><small><?php echo $dados['data']; ?></span></small></p>
					<p><?php echo $dados['tweet']; ?></p>

					<br />
					<form method="post" action="/excluir">
						<?php if($_SESSION['id'] == $dados['id_usuario']) { ?>
						<div class="col d-flex justify-content-end">
						<a href="/excluir?id=<?=$dados['id']?>" class="btn btn-outline-danger"><small>Remover</small></a>
						</div>
						<?php } ?>
					</form>
				</div>
			</div>
<?php } ?>

		<div class="row mt-5">
		<nav aria-label="...">
		<ul class="pagination">
			<li class="page-item disabled <?=$this->view->pagina_ativa == $i ? 'active' : '' ?>">
			<a class="page-link " href="?pagina=1" tabindex="-1">Previous</a>
			</li>
			<?php for($i =1; $i <= $this->view->total_de_paginas; $i++)
			{ ?>
			<li class="page-item <?=$this->view->pagina_ativa == $i ? 'active' : '' ?>"><a class="page-link" href="?pagina=<?php echo $i;?>"><?= $i ?></a></li>
			<?php } ?>
			<li class="page-item <?=$this->view->pagina_ativa == $i ? 'active' : '' ?>">
			<a class="page-link " href="?pagina=<?php echo $this->view->total_de_paginas;?>">Ultima</a>
			</li>
		</ul>
		</nav>
		</div>

		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quemseguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>